# Generated by Django 3.0.5 on 2020-04-25 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('packets', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('rank', models.CharField(max_length=3000)),
                ('removed_packets', models.IntegerField(default=0)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('datesuspended', models.DateField(auto_now_add=True)),
                ('incold', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
