# Generated by Django 3.0.5 on 2020-04-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldentry',
            old_name='datecreated',
            new_name='exported_at',
        ),
        migrations.RenameField(
            model_name='coldentry',
            old_name='datesuspended',
            new_name='imported_at',
        ),
    ]
