# Generated by Django 3.0.5 on 2020-04-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='year',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
