# Generated by Django 3.0.5 on 2020-04-27 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldentry',
            name='diary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.Diary'),
            preserve_default=False,
        ),
    ]
