# Generated by Django 3.0.5 on 2020-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_coldentry_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
